language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t joyful/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joyful/react-test npm test

after_success:
  - docker build -t joyful/multi-client ./client
  - docker build -t joyful/multi-nginx ./nginx
  - docker build -t joyful/multi-server ./server
  - docker build -t joyful/multi-worker ./worker
# Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to Docker Hub
  - docker push joyful/multi-client
  - docker push joyful/multi-nginx
  - docker push joyful/multi-server
  - docker push joyful/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-dev
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY